/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EnhancedSymbolsPrettifier
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/search.ts
var SearchCursor = class {
  constructor(text, regex, _originalCaret) {
    this.text = text;
    this._originalCaret = _originalCaret;
    if (regex instanceof RegExp) {
      this.regex = regex;
    } else {
      this.regex = new RegExp(regex);
    }
    this.reset();
  }
  reset() {
    this._from = this._originalCaret;
    this._to = this._originalCaret;
    this._caret = this._originalCaret;
  }
  findNext() {
    const text = this.text.slice(this._caret);
    const match = text.match(this.regex);
    if ((match == null ? void 0 : match.index) == null) {
      return void 0;
    }
    if (match.length === 4) {
      this._from = this._caret + match.index + match[1].length;
      this._to = this._caret + match.index + match[1].length + match[2].length;
      this._caret = this._to;
      return match;
    }
    this._from = this._caret + match.index;
    this._to = this._caret + match.index + match[0].length;
    this._caret = this._to;
    return match;
  }
  to() {
    return this._to;
  }
  from() {
    return this._from;
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var EnhancedSymbolsPrettifierSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  displayReplacement(replacement, i, containerEl) {
    const value = replacement.value;
    let key = replacement.replaced;
    new import_obsidian.Setting(containerEl).setName(`${i}.`).setDesc(
      `${replacement.count ? replacement.count + " total replacement" + (replacement.count > 1 ? "s" : "") : ""}`
    ).addText(
      (text) => text.setPlaceholder("To replace").setValue(key).onChange((index) => __async(this, null, function* () {
        this.plugin.settings.replacements[key].replaced = index;
        this.plugin.settings.replacements[index] = this.plugin.settings.replacements[key];
        delete this.plugin.settings.replacements[key];
        key = index;
        yield this.plugin.saveSettings();
      }))
    ).addText(
      (text) => text.setPlaceholder("Replace with").setValue(value).onChange((val) => __async(this, null, function* () {
        this.plugin.settings.replacements[key].value = val;
        yield this.plugin.saveSettings();
      }))
    ).addToggle(
      (toggle) => toggle.setValue(!replacement.disabled).onChange((value2) => __async(this, null, function* () {
        this.plugin.settings.replacements[key].disabled = !value2;
        yield this.plugin.saveSettings();
      }))
    ).addButton(
      (button) => button.setIcon("x").onClick(() => __async(this, null, function* () {
        delete this.plugin.settings.replacements[key];
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
  }
  displayGroup(group, containerEl) {
    new import_obsidian.Setting(containerEl).setName(group).setHeading();
    new import_obsidian.Setting(containerEl).setName("Disable group").addToggle(
      (toggle) => toggle.setValue(
        Object.values(this.plugin.settings.replacements).filter((replacement) => replacement.group === group).filter((replacement) => !replacement.disabled).length === 0
      ).onChange((value) => __async(this, null, function* () {
        for (const key in this.plugin.settings.replacements) {
          const replacement = this.plugin.settings.replacements[key];
          if (replacement.group === group) {
            this.plugin.settings.replacements[key].disabled = value;
          }
        }
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    let i = 0;
    for (const key in this.plugin.settings.replacements) {
      const replacement = this.plugin.settings.replacements[key];
      if (replacement.group === group) {
        i++;
        this.displayReplacement(replacement, i, containerEl);
      }
    }
    new import_obsidian.Setting(containerEl).setName("Add new symbol").addButton(
      (button) => button.setButtonText("Add").setCta().onClick(() => __async(this, null, function* () {
        this.plugin.settings.replacements[""] = {
          replaced: "",
          value: "",
          disabled: false,
          group
        };
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("p", {
      text: "Add or remove symbols to prettify in your notes. You can also temporarily disable a symbol by toggling the switch."
    });
    const groups = /* @__PURE__ */ new Set();
    for (const key in this.plugin.settings.replacements) {
      const replacement = this.plugin.settings.replacements[key];
      groups.add(replacement.group);
    }
    for (const group of groups) {
      this.displayGroup(group, containerEl);
    }
    containerEl.createEl("hr");
    let textNewGroup = "";
    new import_obsidian.Setting(containerEl).setName("Add new group").addText(
      (text) => text.setPlaceholder("Group name").onChange((value) => __async(this, null, function* () {
        textNewGroup = value;
      }))
    ).addButton(
      (button) => button.setButtonText("Add").setCta().onClick(() => __async(this, null, function* () {
        const groupName = textNewGroup;
        if (groupName) {
          this.plugin.settings.replacements[""] = {
            replaced: "",
            value: "",
            disabled: false,
            group: groupName
          };
          yield this.plugin.saveSettings();
          this.display();
        }
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Reset statistics").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(() => __async(this, null, function* () {
        for (const key in this.plugin.settings.replacements) {
          delete this.plugin.settings.replacements[key].count;
        }
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Restore settings to default").addButton(
      (button) => button.setButtonText("Restore settings").setWarning().onClick(() => __async(this, null, function* () {
        yield this.plugin.restoreDefaultSettings();
        this.display();
      }))
    );
    containerEl.createEl("p", {
      text: "Made by Noam Schmitt based on the Symbols Prettifier plugin by Florian Woelki."
    });
  }
};

// src/defaultSettings.ts
var DEFAULT_SETTINGS = {
  replacements: {
    "->": {
      replaced: "->",
      value: "\u2192",
      group: "Arrows"
    },
    "<-": {
      replaced: "<-",
      value: "\u2190",
      group: "Arrows"
    },
    "<->": {
      replaced: "<->",
      value: "\u2194",
      group: "Arrows"
    },
    "<=>": {
      replaced: "<=>",
      value: "\u21D4",
      group: "Arrows"
    },
    "=": {
      replaced: "<=",
      value: "\u21D0",
      group: "Arrows"
    },
    "=>": {
      replaced: "=>",
      value: "\u21D2",
      group: "Arrows"
    },
    "=/=": {
      replaced: "=/=",
      value: "\u2260",
      group: "Mathematical Operators"
    },
    "~=": {
      replaced: "~=",
      value: "\u2248",
      group: "Mathematical Operators"
    },
    "----": {
      replaced: "----",
      value: "\u2014",
      group: "Miscellaneous"
    },
    "(c)": {
      replaced: "(c)",
      value: "\xA9",
      group: "Miscellaneous"
    },
    "(r)": {
      replaced: "(r)",
      value: "\xAE",
      group: "Miscellaneous"
    },
    "/!\\": {
      replaced: "/!\\",
      value: "\u26A0",
      group: "Miscellaneous"
    },
    "(1)": {
      replaced: "(1)",
      value: "1\uFE0F\u20E3",
      group: "Numbers"
    },
    "(2)": {
      replaced: "(2)",
      value: "2\uFE0F\u20E3",
      group: "Numbers"
    },
    "(3)": {
      replaced: "(3)",
      value: "3\uFE0F\u20E3",
      group: "Numbers"
    },
    "(4)": {
      replaced: "(4)",
      value: "4\uFE0F\u20E3",
      group: "Numbers"
    },
    "(5)": {
      replaced: "(5)",
      value: "5\uFE0F\u20E3",
      group: "Numbers"
    },
    "(6)": {
      replaced: "(6)",
      value: "6\uFE0F\u20E3",
      group: "Numbers"
    },
    "(7)": {
      replaced: "(7)",
      value: "7\uFE0F\u20E3",
      group: "Numbers"
    },
    "(8)": {
      replaced: "(8)",
      value: "8\uFE0F\u20E3",
      group: "Numbers"
    },
    "(9)": {
      replaced: "(9)",
      value: "9\uFE0F\u20E3",
      group: "Numbers"
    },
    "(10)": {
      replaced: "(10)",
      value: "\u{1F51F}",
      group: "Numbers"
    },
    "(0)": {
      replaced: "(0)",
      value: "0\uFE0F\u20E3",
      group: "Numbers"
    },
    "w/": {
      replaced: "w/",
      value: "with",
      group: "Words"
    },
    "w/o": {
      replaced: "w/o",
      value: "without",
      group: "Words"
    },
    "->>": {
      replaced: "->>",
      value: "\u21C9",
      group: "Arrows"
    },
    "<<-": {
      replaced: "<<-",
      value: "\u21C7",
      group: "Arrows"
    },
    "=>>": {
      replaced: "=>>",
      value: "\u21C9",
      group: "Arrows"
    },
    "<<=": {
      replaced: "<<=",
      value: "\u21C7",
      group: "Arrows"
    },
    "===": {
      replaced: "===",
      value: "\u2261",
      group: "Mathematical Operators"
    },
    "!=": {
      replaced: "!=",
      value: "\u2260",
      group: "Mathematical Operators"
    },
    "=<": {
      replaced: "=<",
      value: "\u2264",
      group: "Mathematical Operators"
    },
    ">=": {
      replaced: ">=",
      value: "\u2265",
      group: "Mathematical Operators"
    },
    "<<": {
      replaced: "<<",
      value: "\u226A",
      group: "Mathematical Operators"
    },
    ">>": {
      replaced: ">>",
      value: "\u226B",
      group: "Mathematical Operators"
    },
    "||": {
      replaced: "||",
      value: "\u2225",
      group: "Mathematical Operators"
    },
    "&&": {
      replaced: "&&",
      value: "\u2227",
      group: "Mathematical Operators"
    },
    "...": {
      replaced: "...",
      value: "\u2026",
      group: "Miscellaneous"
    },
    sqrt: {
      replaced: "sqrt",
      value: "\u221A",
      group: "Mathematical Operators"
    },
    pi: {
      replaced: "pi",
      value: "\u03C0",
      group: "Mathematical Operators"
    },
    inf: {
      replaced: "inf",
      value: "\u221E",
      group: "Mathematical Operators"
    },
    sum: {
      replaced: "sum",
      value: "\u2211",
      group: "Mathematical Operators"
    },
    prod: {
      replaced: "prod",
      value: "\u220F",
      group: "Mathematical Operators"
    },
    delta: {
      replaced: "delta",
      value: "\u0394",
      group: "Greek Letters"
    },
    alpha: {
      replaced: "alpha",
      value: "\u03B1",
      group: "Greek Letters"
    },
    beta: {
      replaced: "beta",
      value: "\u03B2",
      group: "Greek Letters"
    },
    gamma: {
      replaced: "gamma",
      value: "\u03B3",
      group: "Greek Letters"
    },
    epsilon: {
      replaced: "epsilon",
      value: "\u03B5",
      group: "Greek Letters"
    }
  }
};

// src/main.ts
var EnhancedSymbolsPrettifier = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(
        new EnhancedSymbolsPrettifierSettingsTab(this.app, this)
      );
      this.addCommand({
        id: "format-symbols",
        name: "Prettify existing symbols in document",
        editorCallback: (editor) => this.prettifyInDocument(editor)
      });
      this.addCommand({
        id: "format-symbols-reverse",
        name: "Unprettify existing symbols in document",
        editorCallback: (editor) => this.prettifyInDocument(editor, true)
      });
      if (import_obsidian2.Platform.isMobileApp) {
        this.registerDomEvent(window, "keyup", (event) => {
          this.keyDownEvent(event);
        });
      } else {
        this.registerDomEvent(document, "keydown", (event) => {
          this.keyDownEvent(event);
        });
      }
    });
  }
  onunload() {
    return __async(this, null, function* () {
      yield this.saveSettings();
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign(
        {},
        DEFAULT_SETTINGS,
        yield this.loadData()
      );
      this.settings.replacements = Object.assign(
        {},
        DEFAULT_SETTINGS.replacements,
        this.settings.replacements
      );
      this.validateSettings();
    });
  }
  validateSettings() {
    const keys = Object.keys(this.settings.replacements);
    keys.forEach((key) => {
      const replacement = this.settings.replacements[key];
      if (replacement.replaced !== key) {
        this.settings.replacements[replacement.replaced] = replacement;
        delete this.settings.replacements[key];
      }
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      this.validateSettings();
      yield this.saveData(this.settings);
    });
  }
  restoreDefaultSettings() {
    return __async(this, null, function* () {
      this.settings = JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
      yield this.saveSettings();
    });
  }
  getRegex(reverse = false) {
    const matchChars = Object.entries(this.settings.replacements).reduce(
      (prev, [key, replacement]) => {
        const curr = reverse ? replacement.value : replacement.replaced;
        if (prev.length === 0) {
          return prev + this.escapeRegExp(curr);
        } else if (curr.length === 0 || replacement.disabled) {
          return prev;
        }
        return prev + "|" + this.escapeRegExp(curr);
      },
      ""
    );
    return new RegExp(
      "(?<![\\w\xC0-\xD6\xD8-\xF6\xF8-\xFF])(" + matchChars + ")(?![\\w\xC0-\xD6\xD8-\xF6\xF8-\xFF])"
    );
  }
  prettifyInDocument(editor, reverse = false) {
    let value = editor.getValue();
    const codeBlocks = this.getCodeBlocks(value);
    let matchedChars = [];
    const searchCursor = new SearchCursor(
      value,
      this.getRegex(reverse),
      0
    );
    while (searchCursor.findNext() !== void 0) {
      matchedChars.push({
        from: searchCursor.from(),
        to: searchCursor.to()
      });
    }
    matchedChars = matchedChars.filter((matchedChar) => {
      return !codeBlocks.some(
        (cb) => cb.from <= matchedChar.from && cb.to >= matchedChar.to
      );
    });
    let diff = 0;
    let replacementsCount = 0;
    matchedChars.forEach((matchedChar) => {
      var _a;
      const symbol = value.substring(
        matchedChar.from - diff,
        matchedChar.to - diff
      );
      let replacement;
      if (reverse) {
        replacement = (_a = Object.entries(
          this.settings.replacements
        ).find(([, replacement2]) => replacement2.value === symbol)) == null ? void 0 : _a[1];
      } else {
        replacement = this.settings.replacements[symbol];
      }
      if (!replacement) {
        return;
      }
      if (replacement.disabled) {
        return;
      }
      const character = reverse ? replacement.replaced : replacement.value;
      value = value.substring(0, matchedChar.from - diff) + character + value.substring(matchedChar.to - diff);
      diff += symbol.length - character.length;
      replacementsCount++;
      replacement.count = replacement.count ? replacement.count + 1 : 1;
    });
    editor.setValue(value);
    if (replacementsCount === 0) {
      new import_obsidian2.Notice("No symbols found to replace");
    } else if (replacementsCount === 1) {
      new import_obsidian2.Notice("Replaced 1 symbol");
    } else {
      new import_obsidian2.Notice(`Replaced ${replacementsCount} symbols`);
    }
  }
  keyDownEvent(event) {
    var _a;
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (editor) {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      let isSpacebar = false;
      if (import_obsidian2.Platform.isMobileApp) {
        isSpacebar = line.charAt(cursor.ch - 1) === " ";
        cursor.ch = cursor.ch - 1;
      }
      if (event.key === " " || isSpacebar) {
        let from = -1;
        let sequence = "";
        for (let i = cursor.ch - 1; i >= 0; i--) {
          if (line.charAt(i) === " ") {
            const excludeWhitespace = i + 1;
            from = excludeWhitespace;
            sequence = line.slice(excludeWhitespace, cursor.ch);
            break;
          } else if (i === 0) {
            from = i;
            sequence = line.slice(i, cursor.ch);
            break;
          }
        }
        const replacement = this.settings.replacements[sequence];
        if (!replacement) {
          return;
        }
        if (replacement.disabled) {
          return;
        }
        const replaceCharacter = replacement.value;
        if (replaceCharacter && sequence.length > 0 && from !== -1 && typeof replaceCharacter !== "function" && !this.isCursorInUnwantedBlocks(editor)) {
          editor.replaceRange(
            replaceCharacter,
            { line: cursor.line, ch: from },
            { line: cursor.line, ch: cursor.ch }
          );
          replacement.count = replacement.count ? replacement.count + 1 : 1;
        }
      }
    }
  }
  escapeRegExp(string) {
    return string.replace(/[.*+?^!${}()|[<>\]\\]/g, "\\$&");
  }
  getCodeBlocks(input) {
    const result = [];
    const codeBlock = /```\w*[^`]+```/;
    const searchCursor = new SearchCursor(input, codeBlock, 0);
    while (searchCursor.findNext() !== void 0) {
      result.push({ from: searchCursor.from(), to: searchCursor.to() });
    }
    return result;
  }
  isCursorInUnwantedBlocks(editor) {
    const unwantedBlocks = [/(^|[^`])(`[^`\n]+`)([^`]|$)/, /```\w*\s*[\s\S]*?```/];
    return unwantedBlocks.filter((unwantedBlock) => {
      const searchCursor = new SearchCursor(
        editor.getValue(),
        unwantedBlock,
        0
      );
      while (searchCursor.findNext() !== void 0) {
        const offset = editor.posToOffset(editor.getCursor());
        if (searchCursor.from() <= offset && searchCursor.to() >= offset) {
          return true;
        }
      }
      return false;
    }).length !== 0;
  }
};
