matches:
  - trigger: ':now'
    replace: '{{mytime}}'
    vars:
      - name: mytime
        type: date
        params:
          format: '%H:%M'

  # Math superscripts
  - trigger: ':^int'
    replace: 'ᶴ'

  - trigger: ':^='
    replace: '₌'

  - trigger: ':^0'
    replace: '⁰'

  - trigger: ':^1'
    replace: '¹'

  - trigger: ':^2'
    replace: '²'

  - trigger: ':^3'
    replace: '³'

  - trigger: ':^4'
    replace: '⁴'

  - trigger: ':^5'
    replace: '⁵'

  - trigger: ':^6'
    replace: '⁶'

  - trigger: ':^7'
    replace: '⁷'

  - trigger: ':^8'
    replace: '⁸'

  - trigger: ':^9'
    replace: '⁹'

  # Math subscripts
  - trigger: ':_0'
    replace: '₀'

  - trigger: ':_1'
    replace: '₁'

  - trigger: ':_2'
    replace: '₂'

  - trigger: ':_3'
    replace: '₃'

  - trigger: ':_4'
    replace: '₄'

  - trigger: ':_5'
    replace: '₅'

  - trigger: ':_6'
    replace: '₆'

  - trigger: ':_7'
    replace: '₇'

  - trigger: ':_8'
    replace: '₈'

  - trigger: ':_9'
    replace: '₉'

  - trigger: ':_+'
    replace: '₊'

  - trigger: ':_-'
    replace: '₋'

  - trigger: ':_='
    replace: '₌'

  - trigger: ':_('
    replace: '₍'

  - trigger: ':_)'
    replace: '₎'

  # Latin lowercase superscripts
  - trigger: ':^a'
    replace: 'ᵃ'

  - trigger: ':^b'
    replace: 'ᵇ'

  - trigger: ':^c'
    replace: 'ᶜ'

  - trigger: ':^d'
    replace: 'ᵈ'

  - trigger: ':^e'
    replace: 'ᵉ'

  - trigger: ':^f'
    replace: 'ᶠ'

  - trigger: ':^g'
    replace: 'ᵍ'

  - trigger: ':^h'
    replace: 'ʰ'

  - trigger: ':^i'
    replace: 'ⁱ'

  - trigger: ':^j'
    replace: 'ʲ'

  - trigger: ':^k'
    replace: 'ᵏ'

  - trigger: ':^l'
    replace: 'ˡ'

  - trigger: ':^m'
    replace: 'ᵐ'

  - trigger: ':^n'
    replace: 'ⁿ'

  - trigger: ':^o'
    replace: 'ᵒ'

  - trigger: ':^p'
    replace: 'ᵖ'

  - trigger: ':^r'
    replace: 'ʳ'

  - trigger: ':^s'
    replace: 'ˢ'

  - trigger: ':^t'
    replace: 'ᵗ'

  - trigger: ':^u'
    replace: 'ᵘ'

  - trigger: ':^v'
    replace: 'ᵛ'

  - trigger: ':^w'
    replace: 'ʷ'

  - trigger: ':^x'
    replace: 'ˣ'

  - trigger: ':^y'
    replace: 'ʸ'

  - trigger: ':^z'
    replace: 'ᶻ'

  # Latin lowercase subscripts
  - trigger: ':_a'
    replace: 'ₐ'

  - trigger: ':_e'
    replace: 'ₑ'

  - trigger: ':_h'
    replace: 'ₕ'

  - trigger: ':_i'
    replace: 'ᵢ'

  - trigger: ':_j'
    replace: 'ⱼ'

  - trigger: ':_k'
    replace: 'ₖ'

  - trigger: ':_l'
    replace: 'ₗ'

  - trigger: ':_m'
    replace: 'ₘ'

  - trigger: ':_n'
    replace: 'ₙ'

  - trigger: ':_o'
    replace: 'ₒ'

  - trigger: ':_p'
    replace: 'ₚ'

  - trigger: ':_r'
    replace: 'ᵣ'

  - trigger: ':_s'
    replace: 'ₛ'

  - trigger: ':_t'
    replace: 'ₜ'

  - trigger: ':_u'
    replace: 'ᵤ'

  - trigger: ':_v'
    replace: 'ᵥ'

  - trigger: ':_x'
    replace: 'ₓ'

  # Latin uppercase superscripts
  - trigger: ':^A'
    replace: 'ᴬ'

  - trigger: ':^B'
    replace: 'ᴮ'

  - trigger: ':^D'
    replace: 'ᴰ'

  - trigger: ':^E'
    replace: 'ᴱ'

  - trigger: ':^G'
    replace: 'ᴳ'

  - trigger: ':^H'
    replace: 'ᴴ'

  - trigger: ':^I'
    replace: 'ᴵ'

  - trigger: ':^J'
    replace: 'ᴶ'

  - trigger: ':^K'
    replace: 'ᴷ'

  - trigger: ':^L'
    replace: 'ᴸ'

  - trigger: ':^M'
    replace: 'ᴹ'

  - trigger: ':^N'
    replace: 'ᴺ'

  - trigger: ':^O'
    replace: 'ᴼ'

  - trigger: ':^P'
    replace: 'ᴾ'

  - trigger: ':^R'
    replace: 'ᴿ'

  - trigger: ':^T'
    replace: 'ᵀ'

  - trigger: ':^U'
    replace: 'ᵁ'

  - trigger: ':^V'
    replace: 'ⱽ'

  - trigger: ':^W'
    replace: 'ᵂ'

  # Greek superscripts
  - trigger: ':^alpha'
    replace: 'ᵅ'

  - trigger: ':^beta'
    replace: 'ᵝ'

  - trigger: ':^gamma'
    replace: 'ᵞ'

  - trigger: ':^delta'
    replace: 'ᵟ'

  - trigger: ':^epsilon'
    replace: 'ᵋ'

  - trigger: ':^theta'
    replace: 'ᶿ'

  - trigger: ':^iota'
    replace: 'ᶥ'

  - trigger: ':^phi'
    replace: 'ᶲ'

  - trigger: ':^chi'
    replace: 'ᵡ'

  # Greek subscripts
  - trigger: ':_beta'
    replace: 'ᵦ'

  - trigger: ':_gamma'
    replace: 'ᵧ'

  - trigger: ':_chi'
    replace: 'ᵪ'

  # Markdown
  - trigger: ':h1'
    replace: '#'

  - trigger: ':h2'
    replace: '##'

  - trigger: ':h3'
    replace: '###'

  - trigger: ':h4'
    replace: '####'

  - trigger: ':h5'
    replace: '#####'

  - trigger: ':h6'
    replace: '######'

  - trigger: ':url'
    replace: '[$|$]()'

  - trigger: ':img'
    replace: '![]($|$)'

  - trigger: ':-['
    replace: '- [ ] '

  - trigger: ':-[]'
    replace: '- [x] '

  - trigger: ':summary'
    replace: |-
      <details>
      <summary></summary>
      $|$
      </details>
    force_clipboard: true

  # Markdown tables
  - trigger: ':mdt2'
    replace: |-
      |  $|$  |    |
      |:--:|:--:|
      |    |    |
    force_clipboard: true

  - trigger: ':mdt3'
    replace: |-
      |  $|$  |    |    |
      |:--:|:--:|:--:|
      |    |    |    |
    force_clipboard: true

  - trigger: ':mdt4'
    replace: |-
      |  $|$  |    |    |    |
      |:--:|:--:|:--:|:--:|
      |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdt5'
    replace: |-
      |  $|$  |    |    |    |    |
      |:--:|:--:|:--:|:--:|:--:|
      |    |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdt6'
    replace: |-
      |  $|$  |    |    |    |    |    |
      |:--:|:--:|:--:|:--:|:--:|:--:|
      |    |    |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdt7'
    replace: |-
      |  $|$  |    |    |    |    |    |    |
      |:--:|:--:|:--:|:--:|:--:|:--:|:--:|
      |    |    |    |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdt8'
    replace: |-
      |  $|$  |    |    |    |    |    |    |    |
      |:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
      |    |    |    |    |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdt9'
    replace: |-
      |  $|$  |    |    |    |    |    |    |    |    |
      |:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
      |    |    |    |    |    |    |    |    |    |
    force_clipboard: true

  - trigger: ':mdr2'
    replace: '|  $|$  |    |'
    force_clipboard: true

  - trigger: ':mdr3'
    replace: '|  $|$  |    |    |'
    force_clipboard: true

  - trigger: ':mdr4'
    replace: '|  $|$  |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr5'
    replace: '|  $|$  |    |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr6'
    replace: '|  $|$  |    |    |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr7'
    replace: '|  $|$  |    |    |    |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr8'
    replace: '|  $|$  |    |    |    |    |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr9'
    replace: '|  $|$  |    |    |    |    |    |    |    |    |'
    force_clipboard: true

  - trigger: ':mdr10'
    replace: '|  $|$  |    |    |    |    |    |    |    |    |    |'
    force_clipboard: true

  # Markdown code blocks
  - trigger: ':`py'
    replace: "```python\n$|$\n```"

  - trigger: ':`go'
    replace: "```go\n$|$\n```"

  - trigger: ':`rs'
    replace: "```rust\n$|$\n```"

  - trigger: ':`cpp'
    replace: "```cpp\n$|$\n```"

  - trigger: ':`jl'
    replace: "```julia\n$|$\n```"

  - trigger: ':`j'
    replace: "```java\n$|$\n```"

  - trigger: ':`sh'
    replace: "```bash\n$|$\n```"

  - trigger: ':`pw'
    replace: "```powershell\n$|$\n```"

  - trigger: ':`js'
    replace: "```javascript\n$|$\n```"

  - trigger: ':`ts'
    replace: "```typescript\n$|$\n```"

  - trigger: ':`rb'
    replace: "```ruby\n$|$\n```"

  - trigger: ':`jn'
    replace: "```json\n$|$\n```"

  - trigger: ':`yl'
    replace: "```yaml\n$|$\n```"

  - trigger: ':`tl'
    replace: "```toml\n$|$\n```"
